# Generated by Django 3.1 on 2020-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_guns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guns',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/guns/'),
        ),
    ]
