# Generated by Django 3.1 on 2020-08-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200813_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='guns',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AddField(
            model_name='guns',
            name='category',
            field=models.ForeignKey(default='assault-rifle', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
    ]
