# Generated by Django 3.1 on 2020-08-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200815_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guns',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
