# Generated by Django 3.1 on 2020-08-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200815_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knifes',
        ),
    ]
