# Generated by Django 3.1 on 2020-08-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200815_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('sex', models.CharField(db_index=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='static/images/users/')),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
    ]
