# Generated by Django 3.1 on 2020-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_infoofuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoofuser',
            name='body',
            field=models.TextField(db_index=True, default='', max_length=200),
        ),
    ]
