# Generated by Django 3.1 on 2020-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_infoofuser_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoofuser',
            name='login',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
