# Generated by Django 3.1 on 2020-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_infoofuser_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('user', models.CharField(db_index=True, max_length=150)),
                ('gun_slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('date_of_add', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
