# Generated by Django 3.1 on 2020-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_of_add']},
        ),
        migrations.AddField(
            model_name='infoofuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
