# Generated by Django 3.1 on 2020-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200817_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
