# Generated by Django 3.1 on 2020-08-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200817_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoofuser',
            name='cash',
        ),
    ]
