# Generated by Django 3.1 on 2020-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_infoofuser_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoofuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
