# Generated by Django 3.1 on 2020-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_infoofuser_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='gun_slug',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
