# Generated by Django 3.1 on 2020-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='guns',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
