# Generated by Django 3.1 on 2020-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
