# Generated by Django 3.1 on 2020-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200819_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofuser',
            name='image',
            field=models.ImageField(upload_to='static/images/users/'),
        ),
    ]
