# Generated by Django 3.1 on 2020-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200819_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoofuser',
            name='count_of_buy',
            field=models.IntegerField(default=None, max_length=1000),
        ),
    ]
