# Generated by Django 3.1 on 2020-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_infoofuser_count_of_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofuser',
            name='count_of_buy',
            field=models.IntegerField(),
        ),
    ]
