# Generated by Django 3.1 on 2020-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200822_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoofuser',
            name='count_of_buy',
            field=models.IntegerField(default=1),
        ),
    ]
