# Generated by Django 3.1 on 2020-08-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20200822_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoofuser',
            name='count_of_buy',
        ),
    ]
