# Generated by Django 3.1 on 2020-08-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_infoofuser_count_of_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=150)),
                ('user_img', models.ImageField(blank=True, upload_to='static/images/users/')),
                ('body', models.TextField(db_index=True, max_length=200)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.guns')),
            ],
            options={
                'ordering': ['-date_of_add'],
            },
        ),
    ]
