# Generated by Django 3.1 on 2020-08-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20200827_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
