# Generated by Django 3.1 on 2020-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20200827_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gun_main',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
